spring:
  config:
    import: "classpath:application-common.yml"
    activate:
      on-profile: prod

--- # Sentry
sentry:
  dsn: ${SENTRY_DSN}
  exception-resolver-order: -2147483647
  max-request-body-size: always
  send-default-pii: true
  logging:
    enabled: false