spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:yeogiga}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASS:password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      authentication-database: ${MONGODB_AUTH_DB:admin}
      database: ${MONGODB_DATABASE:test}
      username: ${MONGODB_USERNAME:root}
      password: ${MONGODB_PASSWORD:password}

    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASS}