spring:
  profiles:
    active: ${PROFILE:dev}

--- # servlet multipart
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

--- # api link checker
api:
  checker:
    storage:
      filepath: ${user.home}/api-status.json

--- # aws s3
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false
    s3:
      bucket-name: ${S3_BUCKET_NAME}

--- # OAuth2
oauth2:
  naver:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
    redirect-uri: ${NAVER_REDIRECT_URI}
    token-uri: ${NAVER_TOKEN_URI}
    user-info-uri: ${NAVER_USER_INFO_URI}
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: ${KAKAO_REDIRECT_URI}
    token-uri: ${KAKAO_TOKEN_URI}
    user-info-uri: ${KAKAO_USER_INFO_URI}
